# chatjippity help with this one... fingers crossed...
name: Convert Markdown to PDF

on:
  push:
    paths:
      - "**.md"
  pull_request:
    paths:
      - "**.md"

jobs:
  convert-md-to-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get changed Markdown files
        id: changed-files
        run: |
          echo "files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- '*.md' | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_ENV

      - name: Convert Markdown to PDF
        uses: BaileyJM02/markdown-to-pdf@v1.3.0
        with:
          input_dir: .
          output_dir: pdf_output
          files: ${{ env.files }}

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload PDFs to GitHub Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: pdf_output

  deploy:
    needs: convert-md-to-pdf
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
