name: Convert Markdown to PDF

on:
  push:
    paths:
      - "**.md"
  pull_request:
    paths:
      - "**.md"

jobs:
  convert-md-to-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install markdown-to-pdf
        run: npm install -g markdown-to-pdf

      - name: Get changed Markdown files
        id: changed-files
        run: |
          FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- '*.md' || echo "")
          echo "FILES=$FILES" >> $GITHUB_ENV

      - name: Convert Markdown to PDF
        if: env.FILES != ''
        run: |
          mkdir -p pdf_output
          for file in $FILES; do
            markdown-to-pdf "$file" -o "pdf_output/$(basename "$file" .md).pdf"
          done

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload PDFs to GitHub Pages
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: pdf_output

  deploy:
    needs: convert-md-to-pdf
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy PDFs to GitHub Pages
        uses: actions/deploy-pages@v2
