name: Convert Markdown to PDF and Deploy

on:
  push:
    paths:
      - "**.md"  # Trigger workflow on changes to markdown files
  pull_request:
    paths:
      - "**.md"

jobs:
  convert-md-to-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pandoc and LaTeX (for PDF output)
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive

      - name: Get changed Markdown files
        id: changed-files
        run: |
          FILES=$(git diff --name-only HEAD^ HEAD -- '*.md' || echo "")
          echo "FILES=$FILES" >> $GITHUB_ENV

      - name: Convert Markdown to PDF
        if: env.FILES != ''
        run: |
          mkdir -p public/pdf  # Create PDF output folder
          for file in $FILES; do
            pandoc "$file" -o "public/pdf/$(basename "$file" .md).pdf"  # Convert each .md to .pdf
          done

      - name: Deploy to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: public  # Uploads everything in the 'public' directory to GitHub Pages

  deploy:
    needs: convert-md-to-pdf
    runs-on: ubuntu-latest
    permissions:
      pages: write  # Required permission for deploying to GitHub Pages
      id-token: write  # Required for authentication during deployment

    steps:
      - name: Deploy PDFs and content to GitHub Pages
        uses: actions/deploy-pages@v4
