on:
  push:
    paths: 
      - '**.md'
jobs:
  md2pdf:
    runs-on: ubuntu-latest
    name: A job to test this action
    env:
      DEFAULT_DESTINATION: 'Example/build/'
      DEFAULT_OUTPUT: output.document
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: docascod/actions-build@1.0
        with:
          sources: 'Example/*.md'
      - name: Publish
        uses: actions/upload-artifact@v4
        with:
          path: ${{ env.DEFAULT_DESTINATION }}/*.pdf
      - name: Deploy PDFs to GitHub Pages
        uses: actions/deploy-pages@v4.0.5
